"""empty message

Revision ID: 2acc2ace9058
Revises: 013738372a2b
Create Date: 2019-04-20 13:34:52.724928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2acc2ace9058'
down_revision = '013738372a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userinfo', 'department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userinfo', sa.Column('department', mysql.VARCHAR(length=16), nullable=False))
    # ### end Alembic commands ###
