"""
Django settings for django01 project.

Generated by 'django-admin startproject' using Django 1.11.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
#os.path.abspath(__file__)当前文件的绝对路径:/home/tarena/PycharmProjects/django01/django01/setting.py
#os.path.dirname(os.path.abspath(__file__)):/home/tarena/PycharmProjects/django01/django01/
#os.path.dirname(os.path.dirname(os.path.abspath(__file__))):/home/tarena/PycharmProjects/django01/
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
#BASE_DIR表示的是当前项目的绝对路径
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
print("项目绝对路径",BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3j@h9ck7zcs%lkdp-=#f6y68-4a+d=rr6cu9lvsjkr%l7bm(*c'
# 将程序的运行模式改成调试模式
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#设置允许访问到本项目的地址列表
# 如果为空的只能通过本机访问（127.0.0.1/localhost）
#如果允许被外部机器访问的话,此处可以编写为[*]并配合着./manage.py runserver 0.0.0.0:8000
#的方式进行启动
ALLOWED_HOSTS = ['*']


# Application definition
#注册Django中的应用(应用需要先创建在注册最后在使用)
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

#中间件，自定义的中间件的类需要在此注册

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#指定项目的主路由配置文件
ROOT_URLCONF = 'django01.urls'


#模板的配置文件
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
#
WSGI_APPLICATION = 'django01.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
#数据库的配置信息
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

#语言设置，如果需要将项目变成中文的，则将值修改为zh-Hans
LANGUAGE_CODE = 'en-us'
#指定时区，如果要设置成中国时区则将值修改为Asia/Shanghai
TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
